#!/bin/bash

set -eu

cd ${HOME}/dotfiles/files/git
for git_file in .* ; do
  ln -s ${PWD}/${git_file} ${HOME}
done

cd ${HOME}/dotfiles/files/zsh
ln -s ${PWD}/prezto ${HOME}
ln -s ${PWD}/.p10k.zsh ${HOME}
for zsh_file in .* ; do
  ln -s ${PWD}/${zsh_file} ${HOME}
done

